# Generated by Django 5.2.16 on 2026-07-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('device_type', models.CharField(choices=[('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('XBOX', 'Xbox'), ('PC', 'Gaming PC')], max_length=20, verbose_name='نوع دستگاه')),
                ('hourly_price', models.PositiveIntegerField(verbose_name='قیمت هر ساعت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
            ],
        ),
    ]
