# Generated by Django 5.2.16 on 2026-09-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='محل دستگاه'),
        ),
    ]
