# Generated by Django 5.2.16 on 2026-09-06 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='وضعیت قبلی')),
                ('new_status', models.CharField(max_length=20, verbose_name='وضعیت جدید')),
                ('reason', models.TextField(blank=True, verbose_name='دلیل تغییر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservations.reservation', verbose_name='رزرو')),
            ],
        ),
    ]
