# Generated by Django 5.2.16 on 2026-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationhistory',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل تغییر'),
        ),
    ]
