# Generated by Django 5.2.16 on 2026-09-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservationhistory_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'permissions': [('can_view_all_reservations', 'Can view all reservations'), ('can_change_reservation_status', 'Can change reservation status')]},
        ),
    ]
