# Generated by Django 5.2.16 on 2026-08-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'مشتری'), ('MANAGER', 'مدیر')], default='CUSTOMER', max_length=20),
        ),
    ]
